# Declare devices to be used as OSDs
devices:
  - /dev/sdb
# Declare devices to be used as block.db devices
# dedicated_devices:
#   - /dev/sdb

# Declare devices to be used as block.wal devices
bluestore_wal_devices:
  - /dev/sdc
